# Конфигурация ГОСТа. Все единицы указаны в миллиметрах (mm), пунктах (pt) или строках, где применимо.
# Изменяйте эти параметры при необходимости, чтобы соответствовать актуальному ГОСТу БГУИР.

# ─────────────────────────────────────────────────────────────────────────────
# Поля страницы (мм)
margins:
  left: 30      # Левое поле: 30 мм
  right: 15     # Правое поле: 15 мм
  top: 20       # Верхнее поле: 20 мм
  bottom: 20    # Нижнее поле: 20 мм

# ─────────────────────────────────────────────────────────────────────────────
# Шрифт для основного текста
font:
  name: "Times New Roman"
  size: 14           # Размер шрифта (pt)
  bolt: false
  italic: false
  underlined: false
  crossed: false

# ─────────────────────────────────────────────────────────────────────────────
# Параметры абзацев
paragraph:
  first_line_indent_mm: 12.5  # Отступ первой строки: 12.5 мм (1.25 см)
  line_spacing: 1          # Межстрочный интервал: 1.5
  alignment: "justify"      # Выравнивание: "left", "right", "center", "justify"

# ─────────────────────────────────────────────────────────────────────────────
# Стили заголовков
# Каждый уровень заголовка должен соответствовать ГОСТу
headings:
  level_1:
    font_size: 16       # pt
    bold: true
    alignment: "center"
    space_before: 16
    space_after: 18     # pt
  level_2:
    font_size: 14       # pt
    bold: true
    alignment: "justify"
    space_before: 16
    space_after: 8      # pt
  level_3:
    font_size: 14       # pt
    bold: false
    italic: true
    alignment: "justify"
    space_before: 16
    space_after: 6      # pt

# ─────────────────────────────────────────────────────────────────────────────
# Параметры таблиц
tables:
  font_size: 12          # pt
  font_name: "Times New Roman"
  line_spacing: 1.0      # Межстрочный для ячеек
  alignment: "center"

# ─────────────────────────────────────────────────────────────────────────────
# Параметры подписей к изображениям
images:
  caption_font_size: 12  # pt
  caption_font_name: "Times New Roman"
  alignment: "center"

# ─────────────────────────────────────────────────────────────────────────────
# Параметры списка литературы (библиография)
bibliography:
  font_size: 14          # pt
  font_name: "Times New Roman"
  line_spacing: 1.0      # Межстрочный
  template: "«{title}» [Электронный ресурс]. Режим доступа: {url} Дата доступа: {access_date}."

# ─────────────────────────────────────────────────────────────────────────────